/***************************************************************************
 *   efiledlg.cpp                                                          *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class extends the file dialog box associated with the Qt4 user     *
 * interface.                                                              *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "efiledlg.h"
#include "../../libanalyzer/analyzer.h"

energyFileDialog::energyFileDialog(QWidget* parent, const QString& caption, const QString& directory,
                                   const QString& filter)
                 :QFileDialog(parent, caption, directory, filter) {
  setOption(QFileDialog::DontUseNativeDialog);

  // add extra parts to standard dialog box
  energyLayout = new QHBoxLayout();
  dataTypeBox = new QComboBox();
  minEnergyBox = new QLineEdit();
  maxEnergyBox = new QLineEdit();

  energyLayout->addWidget(new QLabel(tr("Minimum Energy:")));
  energyLayout->addWidget(minEnergyBox);
  energyLayout->addWidget(new QLabel(tr("Maximum Energy:")));
  energyLayout->addWidget(maxEnergyBox);

  QGridLayout *gridbox = qobject_cast<QGridLayout*>(layout());
  if (gridbox) {
    int rows = gridbox->rowCount();
    
    gridbox->addWidget(new QLabel(tr("Data Type:")),rows+1,0,1,1);
    gridbox->addWidget(dataTypeBox,rows+1,1,1,-1);
    gridbox->addLayout((QLayout*)energyLayout,rows+2,0,1,-1);
  }
  setLayout(gridbox);
  
  analyzer_data_t dataTypes = ANALYZER_NONE;
  int types = static_cast<int>(dataTypes);
  unsigned int loadedTypes = 0;
  analyzer_hdl hdl = -1;
  
  // add all of the appropriate data types to the combo box list
  while (dataTypes != ANALYZER_DATA_LIMIT)
  {
    if (dataTypes == ANALYZER_NONE ||                 // these file types are not opened or saved as a I/O file
        dataTypes == ANALYZER_WEIGHTED_SKY ||
        dataTypes == ANALYZER_WEIGHTED_PIXEL ||
        dataTypes == ANALYZER_PIXEL_OCCUPANCY ||
        dataTypes == ANALYZER_WEIGHTED_INVERSE ||
        dataTypes == ANALYZER_MAP_LIMIT ||
        dataTypes == ANALYZER_WEIGHTED_TRANSFORM ||
        dataTypes == ANALYZER_GRAPH_LIMIT ||
        dataTypes == ANALYZER_TRANSFORM_LIMIT) {
      dataTypes = static_cast<analyzer_data_t>(++types);
      continue;
    }
    
    QString dataName = QString(analyzer_get_datatype(dataTypes));
    dataTypeBox->addItem(dataName);
    dataTypes = static_cast<analyzer_data_t>(++types);
  }

  setAcceptMode(QFileDialog::AcceptOpen);
}
