/***************************************************************************
 *   csvmanager.h                                                          *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   daniel.suson@purduecal.edu                                            *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This header provides the definitions for various enumerated lists used  *
 * by the data classes.                                                    *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#ifndef __CSVMANAGER_H__
#define __CSVMANAGER_H__

#include <fstream>
#include <map>
#include "atypes.h"
#include "filemanager.h"
#include "association.h"
#include "vectordata.h"
#include "matrixdata.h"
#include "cubedata.h"
#include "../libgraphics/datamap.h"
#include "../libgraphics/dataspectrum.h"

#define CSV_ERR_LEN	160

class csvManager : public fileManager {
  public:
    csvManager(association *dataMgr, const char *filename, FILETYPE dataType=fileType::InputData, RWMode mode=Read);
    csvManager(association *dataMgr, const char *filename, baseData *data);
    csvManager(csvManager* from);
    ~csvManager();

    baseData *data();
    inputMatrixData *data(int slice_min, int slice_max);
    inputMatrixData *data(float minE, float maxE);
    std::string keyValue(string key) {return m_headerData[key];}

    void open();
    void save(FILETYPE dataType);
    void save(ASSOCIATEDMAP map);
    void save(ASSOCIATEDSPECTRUM spect);
    std::fstream* filePtr() const {return m_ptr;}
    std::map<string,string> headerData() {return m_headerData;}

  private:
    bool getHeaders(int hdrNum = -1);
    bool getDimensions();
    bool getDataType();
    bool getEnergy();

    baseData     *getVectorI();
    baseData     *getVectorD();
    baseData     *getMatrixD();
    baseData     *getCubeCD();
    dataMap      *getMap();
    dataSpectrum *getSpectrum();

    bool saveBase(const char* filename);
    bool saveVectorI(vectorData<int> *vd);
    bool saveVectorD(vectorData<double> *vd);
    bool saveMatrixD(matrixData<double> *md);
    bool saveCubeCD(cubeData<complex<double> > *cd);
    bool saveMap(dataMap *map);
    bool saveSpectrum(dataSpectrum *spect);
    
    std::string convertString(std::string inString);

    association  *s_association;
    std::fstream *m_ptr;
    std::map<string,string> m_headerData;
    char         csv_err[CSV_ERR_LEN];
};

#endif /* __CSVMANAGER_H__ */
